[platformio]
default_envs = heltec_wifi_lora_32_V3

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
framework = arduino
monitor_speed = 115200
upload_port = COM5   
lib_deps = 
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    heltecautomation/Heltec ESP32 Dev-Boards @ ^1.1.1
